# Generated by Django 4.2 on 2023-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('occupation', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
